Add 0 to allowed package name characters
bazelbuild/rules_kotlin pull request #364
Opened 2020-09-03 06:36 UTC by jyuhengwei

For some unknown reason, `0` is the only alphanumeric character that wasn't recognized as in a package name. This led to odd scenarios that when you tried to compile code that had a `0` in the package name, the kotlin builder would package the code as the string before the `0` which led to some problems in auto-generated code.

2020-09-03 06:37 UTC, jyuhengwei commented
@googlebot I signed it!

2020-09-03 12:35 UTC, restingbull requested changes
Add a test, so we don't do this again?

2020-09-03 19:31 UTC, jyuhengwei commented
> Add a test, so we don't do this again?

I added a test.

2020-09-08 19:25 UTC, jyuhengwei commented
@restingbull Any chance of a re-review?

2020-09-08 19:45 UTC, restingbull commented
Apologies, missed the email.

2020-09-08 19:46 UTC, restingbull approved these changes

2020-09-08 21:43 UTC, jyuhengwei commented
> Apologies, missed the email.

No problem. It happens.

2020-09-09 19:40 UTC, jyuhengwei commented
@restingbull Do I need to do something else to get this merged?

2020-09-09 21:21 UTC, merged

2020-09-09 21:22 UTC, restingbull commented
Apologies -- I forgot you can't merge it.

On Wed, Sep 9, 2020 at 3:40 PM jyuhengwei <notifications@github.com> wrote:

> @restingbull <https://github.com/restingbull> Do I need to do something
> else to get this merged?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_kotlin/pull/364#issuecomment-689775706>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN3VGM6GRHY6RNZGMT3JKSDSE7K3HANCNFSM4QUMM6BA>
> .
>