Support -Xno-optimized-callable-references kotlinc flag
bazelbuild/rules_kotlin pull request #394
Opened 2020-11-16 19:00 UTC by Bencodes

https://github.com/JetBrains/kotlin/blob/68fdeaf865f279cb7a75eaec7e9f4e6cd0646707/compiler/testData/cli/jvm/extraHelp.out#L77-L78

2020-11-18 18:23 UTC, Bencodes commented
Rebased this one

2020-12-04 16:25 UTC, restingbull requested changes
Add a check in (_kotlin_toolchain_impl)[ https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/toolchains.bzl#L49] on the version number is greater than 1.4

2020-12-04 16:25 UTC, restingbull commented on kotlin/internal/opts.bzl
> +            doc = "Do not use optimized callable reference superclasses available from 1.4.",
nit: "Do not use optimized callable reference superclasses. Available from 1.4."

2020-12-04 20:51 UTC, Bencodes commented
It would probably make more sense to do the validation in `_kotlinc_options_provider_to_flags` so that we can also validate the target level opts that aren't being consumed directly by the toolchain.

2020-12-05 15:59 UTC, restingbull commented
> It would probably make more sense to do the validation in `_kotlinc_options_provider_to_flags` so that we can also validate the target level opts that aren't being consumed directly by the toolchain.

Reasonable, considering https://github.com/bazelbuild/rules_kotlin/pull/418.

2020-12-09 22:38 UTC, Bencodes commented on kotlin/internal/jvm/compile.bzl
> +    language_versions = {p.language_version: True for p in providers if p.language_version}
There seems to have been a typo here

2020-12-09 22:38 UTC, Bencodes commented
Updated with some basic validation

2020-12-19 17:10 UTC, restingbull approved these changes

2020-12-19 17:11 UTC, restingbull commented
Is it me, or the kotlinc flags getting longer?

2020-12-24 01:20 UTC, Bencodes commented
Rebased this after all the kotlinc merges.

2020-12-24 16:56 UTC, restingbull commented
Ah, thanks. Meant to rebase the pr and got distracted.

2020-12-24 16:56 UTC, merged